# Generated by Django 4.1.1 on 2022-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("birthdate", models.CharField(max_length=200, null=True)),
                ("gender", models.CharField(max_length=200, null=True)),
                ("is_active", models.CharField(max_length=200, null=True)),
                ("data_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
